[project]
name = "foundations-of-ml"
description = "CIROH DevCon 2026 Foundations of Machine Learning workshop"
version = "0.1.0"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [
    { name = "Leo Lonzarich", email = "lglonzaric@gmail.com" },
    { name = "Savalan Neisary", email = "savalan.neisary@gmail.com" },
]
maintainers = [
    { name = "Leo Lonzarich", email = "lglonzaric@gmail.com" },
    { name = "Savalan Neisary", email = "savalan.neisary@gmail.com" },
]
requires-python = ">=3.10.0"
keywords = [
    "pytorch",
    "hydrology",
    "deep-learning",
    "scientific-computing",
]
dependencies = [
    "geopandas",
    "ipykernel",
    "matplotlib",
    "numpy",
    "pandas",
    "pyarrow",
    "scikit-learn",
    "scipy",
    "torch",
    "tqdm",
]

[tool.setuptools.packages.find]
include = []
